export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const REQUEST_FAIL = 'REQUEST_FAIL'

export const SHOW_MODAL = 'SHOW_MODAL'

export const EVENT_FORM_CHANGE = 'EVENT_FORM_CHANGE'
export const EVENT_BTN_CLICKED = 'EVENT_BTN_CLICKED'

export const POPULATE_EVENTS_SUCCESS = 'POPULATE_EVENTS_SUCCESS'
export const REMOVE_EVENT = 'REMOVE_EVENT'

export const LOADING = 'LOADING'

export const POPULATE_BOOKINGS_SUCCESS = 'POPULATE_BOOKINGS_SUCCESS'
export const BOOK_EVENT_SUCCESS = 'BOOK_EVENT_SUCCESS'
export const BOOKING_BTN_CLICKED = 'BOOKING_BTN_CLICKED'
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS'

export const LOG_OUT = 'LOG_OUT'